---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: data
spec:
  type: LoadBalancer
  ports:
    - name: db-port
      port: 3306
      targetPort: mysql # Updated to match the deployment
  selector:
    app: mariadb